db.createCollection("bids",{validator:{
    $jsonSchema:{
        bsonType:"object",
        additionalProperties:false,
        required:["user","orderId","price"],
        properties:{
            _id:{
                bsonType:"objectId",
                description:"error with objectId"
            },
            user:{
                bsonType:"object",
                required:["name","email","mobile","userId"],
                properties:{
                    name:{
                        bsonType:"string",
                        minLength:2,
                        maxLength:60
                    },
                    email:{
                        bsonType:"string",
                        minLength:5,
                        maxLength:80
                    },
                    mobile:{
                        bsonType:"string",
                        minLength:4,
                        maxLength:30
                    },
                    userId:{
                        bsonType:"objectId"
                    }
                }
            },
            orderId:{
                bsonType:"objectId"
            },
            price:{
                bsonType:"double",
                minimum:1,
                maximum:1000000000
            },
            status:{
                enum:["Active","Accepted","Rejected","Finished"]
            },
            removed:{
                bsonType:"bool"
            },
            createdAt:{
                bsonType:"date"
            }
        }
    }
}})