db.createCollection("categories",{validator:{
    $jsonSchema:{
        bsonType:"object",
        additionalProperties:false,
        required:["title","type","createdBy"],
        properties:{
            _id:{
                bsonType:"objectId",
                description:"error with objectId"
            },
            title:{
                bsonType:"string",
                maxLength:40,
                minLength:2
            },
            type:{
                bsonType:"object",
                required:["_id"],
                properties:{
                    _id:{
                        bsonType:"objectId"
                    },
                    title:{
                        bsonType:"string",
                        maxLength:40,
                        minLength:2
                    },
                    hscode:{
                        bsonType:"string",
                        minLength:2,
                        maxLength:2
                    }
                },
                additionalProperties:false
            },
            createdBy:{
                bsonType:"objectId"
            },
            hscode:{
                bsonType:"string",
                minLength:4,
                maxLength:4
            },
            createdAt:{
                bsonType:"date"
            },
            modified:{
                bsonType:"array",
                additionalItems:false,
                items:{
                    bsonType:"object",
                    properties:{
                        modifiedBy:{
                            bsonType:"objectId"
                        },
                        modifiedAt:{
                            bsonType:"date"
                        }
                    }
                }
            }
        }
    }
}})